banet = dict(
    lr_start = 5e-2,
    weight_decay= 5e-4,
    warmup_iters = 0,
    start_epoch = 0,
    epoch = 360,
    im_root= PATH_TO_DATASET,
    train_im_anns='../banet/datasets/cityscapes/train.txt',
    val_im_anns='../banet/datasets/cityscapes/val.txt',
    scales=[0.25, 2.],
    cropsize=[1024, 1024],
    ims_per_gpu=8,
    use_fp16=True,
    use_sync_bn=False,
    respth='./res',
)
